 MANUALLY CREATE A TRANSACTION DATABASE

In [1]:
dataset = [['milk','onion','nescafe','kitkat','eggs','yogurt'],
           ['dairy milk','onion','nescafe','kitkat','eggs','yogurt'],
           ['milk','apple','kitkat','eggs'],
           ['milk','uday','corn','kitkat','yogurt'],
           ['corn','onion','onion','kitkat','ice cream','eggs']]

print(dataset)

[['milk', 'onion', 'nescafe', 'kitkat', 'eggs', 'yogurt'], ['dairy milk', 'onion', 'nescafe', 'kitkat', 'eggs', 'yogurt'], ['milk', 'apple', 'kitkat', 'eggs'], ['milk', 'uday', 'corn', 'kitkat', 'yogurt'], ['corn', 'onion', 'onion', 'kitkat', 'ice cream', 'eggs']]

THE INBUILT APRIORI ALG EXPECTS DATASET IN ONE-HOT ENCODED PANDAS DATAFRAME, SO WE USE MLXTEND PYTHON LIBRARY

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_data=te.fit_transform(dataset)
te_data

array([[False, False, False,  True, False,  True,  True,  True,  True,
        False,  True],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False,  True],
       [ True, False, False,  True, False,  True,  True, False, False,
        False, False],
       [False,  True, False, False, False,  True,  True, False, False,
         True,  True],
       [False,  True, False,  True,  True,  True, False, False,  True,
        False, False]])

In [3]:
df = pd.DataFrame(te_data, columns=te.columns_)
df

,apple,corn,dairy milk,eggs,ice cream,kitkat,milk,nescafe,onion,uday,yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [4]:
from mlxtend.frequent_patterns import apriori

freq_itemset = apriori(df, min_support=0.6, use_colnames = True)

freq_itemset

    support               itemsets
0       0.8                 (eggs)
1       1.0               (kitkat)
2       0.6                 (milk)
3       0.6                (onion)
4       0.6               (yogurt)
5       0.8         (kitkat, eggs)
6       0.6          (eggs, onion)
7       0.6         (milk, kitkat)
8       0.6        (kitkat, onion)
9       0.6       (yogurt, kitkat)
10      0.6  (kitkat, eggs, onion)

In [5]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(freq_itemset, metric = "confidence", min_threshold=0.8)
rules

/usr/local/lib/python3.11/dist-packages/mlxtend/frequent_patterns/association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(kitkat),(eggs),1.0,0.8,0.8,0.8,1.00,1.0,0.00,1.0,0.0,0.80,0.0,0.900
1,(eggs),(kitkat),0.8,1.0,0.8,1.0,1.00,1.0,0.00,inf,0.0,0.80,0.0,0.900
2,(onion),(eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
3,(milk),(kitkat),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
4,(onion),(kitkat),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
5,(yogurt),(kitkat),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
6,"(kitkat, onion)",(eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
7,"(eggs, onion)",(kitkat),0.6,1.0,0.6,1.0,1.00,1.0,0.00,inf,0.0,0.60,0.0,0.800
8,(onion),"(kitkat, eggs)",0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875

In [7]:
# to check the running time for both apriori and fpgrowth and compare

from mlxtend.frequent_patterns import apriori

%timeit apriori(df, min_support=0.6)

1.85 ms ± 317 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)