 MANUALLY CREATE A TRANSACTION DATABASE

In [ ]:
import pandas as pd
import numpy as np
%pip install mlxtend --upgrade             # sometimes colab throws error in installing mlxtend , use this command
!pip install mlxtend
import mlxtend.frequent_patterns
from mlxtend.frequent_patterns import fpgrowth

Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.5.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.5.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
dataset = [['milk','onion','nescafe','kitkat','eggs','yogurt'],
           ['dairy milk','onion','nescafe','kitkat','eggs','yogurt'],
           ['milk','apple','kitkat','eggs'],
           ['milk','uday','corn','kitkat','yogurt'],
           ['corn','onion','onion','kitkat','ice cream','eggs']]

print(dataset)

[['milk', 'onion', 'nescafe', 'kitkat', 'eggs', 'yogurt'], ['dairy milk', 'onion', 'nescafe', 'kitkat', 'eggs', 'yogurt'], ['milk', 'apple', 'kitkat', 'eggs'], ['milk', 'uday', 'corn', 'kitkat', 'yogurt'], ['corn', 'onion', 'onion', 'kitkat', 'ice cream', 'eggs']]

THE INBUILT APRIORI ALG EXPECTS DATASET IN ONE-HOT ENCODED PANDAS DATAFRAME, SO WE USE MLXTEND PYTHON LIBRARY

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_data = te.fit_transform(dataset)
te_data

array([[False, False, False,  True, False,  True,  True,  True,  True,
        False,  True],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False,  True],
       [ True, False, False,  True, False,  True,  True, False, False,
        False, False],
       [False,  True, False, False, False,  True,  True, False, False,
         True,  True],
       [False,  True, False,  True,  True,  True, False, False,  True,
        False, False]])

In [ ]:
df = pd.DataFrame(te_data)
df

      0      1      2      3      4     5      6      7      8      9      10
0  False  False  False   True  False  True   True   True   True  False   True
1  False  False   True   True  False  True  False   True   True  False   True
2   True  False  False   True  False  True   True  False  False  False  False
3  False   True  False  False  False  True   True  False  False   True   True
4  False   True  False   True   True  True  False  False   True  False  False

In [ ]:
df = pd.DataFrame(te_data, columns=te.columns_)
df

,apple,corn,dairy milk,eggs,ice cream,kitkat,milk,nescafe,onion,uday,yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

freq_itemset = fpgrowth(df, min_support=0.6 , use_colnames= True)
freq_itemset

    support               itemsets
0       1.0               (kitkat)
1       0.8                 (eggs)
2       0.6               (yogurt)
3       0.6                (onion)
4       0.6                 (milk)
5       0.8         (kitkat, eggs)
6       0.6       (kitkat, yogurt)
7       0.6          (onion, eggs)
8       0.6        (onion, kitkat)
9       0.6  (onion, kitkat, eggs)
10      0.6         (kitkat, milk)

In [ ]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(freq_itemset, metric = "confidence", min_threshold=0.8)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(kitkat),(eggs),1.0,0.8,0.8,0.8,1.00,0.00,1.0
1,(eggs),(kitkat),0.8,1.0,0.8,1.0,1.00,0.00,inf
2,(yogurt),(kitkat),0.6,1.0,0.6,1.0,1.00,0.00,inf
3,(onion),(eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf
4,(onion),(kitkat),0.6,1.0,0.6,1.0,1.00,0.00,inf
5,"(onion, kitkat)",(eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf
6,"(onion, eggs)",(kitkat),0.6,1.0,0.6,1.0,1.00,0.00,inf
7,(onion),"(kitkat, eggs)",0.6,0.8,0.6,1.0,1.25,0.12,inf
8,(milk),(kitkat),0.6,1.0,0.6,1.0,1.00,0.00,inf

In [ ]:
# to check the running time for both apriori and fpgrowth and compare

from mlxtend.frequent_patterns import fpgrowth

%timeit fpgrowth(df, min_support=0.6)

1000 loops, best of 5: 1.71 ms per loop